language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-django$DJANGO_VERSION | tr -d .)
install:
  - pip install tox
