language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install tox jasmine
script:
    - tox -e $(echo py$TRAVIS_PYTHON_VERSION-django$DJANGO_VERSION | tr -d .)
    - jasmine-ci
